### ISSUE TITLE
Geospatial bindings don't generate successfully on github version?

### ISSUE THREAD

**Issue by shongololo** [pabigot/pyxb#28]
I've noticed that when trying to generate the geospatial bindings:

The source forge version generates successfully, whereas the github versions (master or development versions) don't? Unfortunately I don't remember the exact error.

**Comment by pabigot** [comment]
Since the SF master and github master are identical, this is odd.  I've just confirmed it works for me on the internal development version, and it worked when I released the master version.

When you remember the exact error and can reproduce it with an up-to-date download from  http://schemas.opengis.net/SCHEMAS_OPENGIS_NET.tgz please feel free to re-open this and provide that information.

**Comment by shongololo** [comment]
Hi, here you go, I downloaded the github version again and this is the error message I receive.

Exception generating bindings: http://www.w3.org/1999/xlink has no category attributeGroupDefinition
Traceback (most recent call last):
  File "/Users/shongololo/Downloads/pyxb-master/pyxb/namespace/__init__.py", line 307, in categoryMap
    return self.__categoryMap[category]
KeyError: 'attributeGroupDefinition'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shongololo/Downloads/pyxb-master/scripts/pyxbgen", line 65, in <module>
    modules = generator.bindingModules()
  File "/Users/shongololo/Downloads/pyxb-master/pyxb/binding/generate.py", line 2865, in bindingModules
    self.__resolveComponentDependencies()
  File "/Users/shongololo/Downloads/pyxb-master/pyxb/binding/generate.py", line 2725, in __resolveComponentDependencies
    pyxb.namespace.resolution.ResolveSiblingNamespaces(namespaces)
  File "/Users/shongololo/Downloads/pyxb-master/pyxb/namespace/resolution.py", line 327, in ResolveSiblingNamespaces
    if not ns.resolveDefinitions(allow_unresolved=True):
  File "/Users/shongololo/Downloads/pyxb-master/pyxb/namespace/resolution.py", line 223, in resolveDefinitions
    resolvable._resolve()
  File "/Users/shongololo/Downloads/pyxb-master/pyxb/xmlschema/structures.py", line 2540, in _resolve
    return self.__completeProcessing(self.__pendingDerivationMethod, self.__contentStyle)
  File "/Users/shongololo/Downloads/pyxb-master/pyxb/xmlschema/structures.py", line 2082, in __completeProcessing
    agd = ag_en.attributeGroupDefinition()
  File "/Users/shongololo/Downloads/pyxb-master/pyxb/namespace/__init__.py", line 104, in __getattr__
    category_value = ns.categoryMap(name).get(self.localName())
  File "/Users/shongololo/Downloads/pyxb-master/pyxb/namespace/__init__.py", line 309, in categoryMap
    raise pyxb.NamespaceError(self, '%s has no category %s' % (self, category))
pyxb.exceptions_.NamespaceError: http://www.w3.org/1999/xlink has no category attributeGroupDefinition
Failed: gml_3_2

**Comment by pabigot** [comment]
Back in 2012 the official schemas switched to using the W3C version of XLink instead of OpenGIS's non-standard version, and the pyxb generation depends on that being available.  You may need to generate the `common` bindings first, and make sure you use the current schemas bundle from the link I noted above.

This command should generate everything:

    maintainer/genbundles @ opengis

The script replaces @ with the schemas for core namespaces used by other complex schemas.  You could try just using `common` but that's not now I build them so I can't say whether it'd work.

**Comment by shongololo** [comment]
This method works, thanks.

**Comment by pabigot** [comment]
Re-opening to remind me to update the opengis README.txt based on the discoveries in this issue.
