### ISSUE TITLE
LogicError only when RequireValidWhenGenerating is False

### ISSUE THREAD

**Issue by amrali** [pabigot/pyxb#47]
I've set `pyxb.RequireValidWhenGenerating(False)` at the top of my module so that it disables the expensive validation step when generating an XML document (it takes ~200ms). But the call `toxml()` always fails with the following exception:

```
Traceback (most recent call last):
  File "somescript.py", line 236, in send_request
    request.toxml()
  File "/usr/local/lib/python3.4/dist-packages/pyxb/binding/basis.py", line 543, in toxml
    dom = self.toDOM(bds, element_name=element_name)
  File "/usr/local/lib/python3.4/dist-packages/pyxb/binding/basis.py", line 514, in toDOM
    self._toDOM_csc(bds, element)
  File "/usr/local/lib/python3.4/dist-packages/pyxb/binding/basis.py", line 2663, in _toDOM_csc
    content.elementDeclaration.toDOM(dom_support, parent, content.value)
  File "/usr/local/lib/python3.4/dist-packages/pyxb/binding/content.py", line 1106, in toDOM
    raise pyxb.LogicError('toDOM with unrecognized value type %s: %s' % (type(value), value))
pyxb.exceptions_.LogicError: toDOM with unrecognized value type <class 'pyxb.binding.content._PluralBinding'>: [<request.EConfirmTradeType object at 0x7f46f5c8b898>]
```

The relevant XSD bits for `EConfirmTradeType` used to generate the data bindings:

```
248    <xs:complexType name="EConfirmRequestType">
249       <xs:sequence>
250          <xs:element name="EConfirmTrade" type="EConfirmTradeType" maxOccurs="unbounded"/>
251       </xs:sequence>
252       <xs:attribute name="BatchId" type="xs:unsignedLong"/>
253    </xs:complexType>
```

```
 517    <xs:complexType name="EConfirmTradeType">
 518       <xs:all>
 519          <xs:element name="SubmissionCompany" type="xs:string" minOccurs="0"/>
 520          <xs:element name="SenderTradeRefId" type="xs:string"/>
 521          <xs:element name="ClientVersionId" type="xs:string" minOccurs="0"/>
 522          <xs:element name="Action" type="ActionType" minOccurs="0"/>
 523          <xs:element name="Comment" type="xs:string" minOccurs="0">
 524             <xs:annotation>
 525                <xs:documentation>Comment supports "Dispute" actions to accomodate
 526                   automated
 527                   match breaks.
 528                </xs:documentation>
 529             </xs:annotation>
 530          </xs:element>
 531          <xs:element name="Type" type="CancelDisputeType" minOccurs="0"/>
 532          <xs:element name="TradeDetail" type="TradeDetailType" minOccurs="0"/>
 533       </xs:all>
 534    </xs:complexType>
```

The element in question is added in code as:

```
econfirm_request = request.EConfirmRequest()
econfirm_trade = request.EConfirmTradeType()
# A bunch of assignment statements for sub-elements of econfirm_trade go here
econfirm_request.append(econfirm_trade)
```

Passing `True` to `RequireValidWhenGenerating` or not making that call (I get that the default behavior is to enable validation when generating XML documents) results in a successful `toxml()` call.

I'm not sure where to begin looking, any ideas?

**Comment by pabigot** [comment]
I can't identify a version of PyXB that matches this line:

    File "/usr/local/lib/python3.4/dist-packages/pyxb/binding/basis.py", line 2663, in _toDOM_csc
        content.elementDeclaration.toDOM(dom_support, parent, content.value)

What version (or commit id) are you using?

**Comment by amrali** [comment]
I'm using version 1.2.4 (the latest version on PyPI)

**Comment by pabigot** [comment]
Weird.  The line numbers don't match my copy of 1.2.4.  In the backtrace the code is off by one line for the first two call sites, and two lines for the third.  PyXB isn't really intended to work without validation and doesn't test for that use case; probably there's an unhandled case related to plural elements.  If I can reproduce it quickly I'll fix it in the next branch here on github, but I don't know when it'll get into a PyPI release.
