### ISSUE TITLE
Unable to check value constraint due to incomplete resolution of type

### ISSUE THREAD

**Issue by CausticYarn** [pabigot/pyxb#72]
I am trying to use pyxb 1.2.5 parse the schema at:

https://www.ebu.ch/metadata/schemas/EBUCore/ebucore.xsd

However I am getting the following error 

    ERROR:pyxb.xmlschema.structures:Unable to check value constraint on {urn:ebu:metadata-schema:ebuCore_2016}technicalAttributeRational due to incomplete resolution of type
    Exception generating bindings: Value constraint on element {urn:ebu:metadata-schema:ebuCore_2016}technicalAttributeRational with non-simple type {urn:ebu:metadata-schema:ebuCore_2016}technicalAttributeRationalType
    Traceback (most recent call last):
      File "C:\pyenv\dev27\Scripts\pyxbgen", line 65, in <module>
        modules = generator.bindingModules()
      File "C:\pyenv\dev27\lib\site-packages\pyxb\binding\generate.py", line 2871, in bindingModules
        self.__resolveComponentDependencies()
      File "C:\pyenv\dev27\lib\site-packages\pyxb\binding\generate.py", line 2731, in __resolveComponentDependencies
        pyxb.namespace.resolution.ResolveSiblingNamespaces(namespaces)
      File "C:\pyenv\dev27\lib\site-packages\pyxb\namespace\resolution.py", line 327, in ResolveSiblingNamespaces
        if not ns.resolveDefinitions(allow_unresolved=True):
      File "C:\pyenv\dev27\lib\site-packages\pyxb\namespace\resolution.py", line 223, in resolveDefinitions
        resolvable._resolve()
      File "C:\pyenv\dev27\lib\site-packages\pyxb\xmlschema\structures.py", line 1734, in _resolve
        self._typeDefinition(td)
      File "C:\pyenv\dev27\lib\site-packages\pyxb\xmlschema\structures.py", line 1502, in _typeDefinition
        raise pyxb.SchemaValidationError('Value constraint on element %s with non-simple type %s' % (self.expandedName(), self.__typeExpandedName))
    SchemaValidationError: Value constraint on element {urn:ebu:metadata-schema:ebuCore_2016}technicalAttributeRational with non-simple type {urn:ebu:metadata-schema:ebuCore_2016}technicalAttributeRationalType

The schema is valid in Altova's XML Spy. I found that the `technicalAttributeRational` is defined in the `technicalAttribute` group and the `technicalAttributeRationalType` is defined later in the document. If I move the `technicalAttribute` group below the `technicalAttributeRationalType`, pyxb is able to parse the schema successfully.

Is this a problem with the schema or a problem with pyxb?

**Comment by pabigot** [comment]
Initial review suggests it's a problem with PyXB, possibly because of insufficient recursion to determine types (`{urn:ebu:metadata-schema:ebuCore_2016}technicalAttributeRationalType` is an extension of `rationalType` in the same namespace).  I'll take a look next time I'm working PyXB.
